name: ping_aredblock
main: main.Main
api-version: 1.13
version: 0.1
commands:
   ping:
      description: View your "Ping"!
      usage: /ping
   search-ping:
      description: View all "Pings"!
      usage: /search-ping
