name: Simping
main: main.Main
api-version: 1.13
version: 1.0
commands:
   ping:
      description: view your ping!
      usage: /ping
   search-ping:
      description: search ping!
      usage: /search-ping
